### ISSUE TITLE
How to initiate this package?

### ISSUE THREAD

**Issue by Heqma** [chinleung/laravel-multilingual-routes#51] opened 2021-06-01 11:41 UTC
"
UnexpectedValueException
Invalid route action: [App\Http\Controllers\FrontController].

`App\Http\Controllers\FrontController` is not invokable.
The controller class App\Http\Controllers\FrontController is not invokable. Did you forget to add the __invoke method or is the controller's method missing in your routes file?"

controller
```
Route::redirect('/', locale());
Route::multilingual('/', 'FrontController')->name('index');
```

**Comment by chinleung** [comment] 2021-06-01 12:23
> The controller class App\Http\Controllers\FrontController is not invokable. Did you forget to add the __invoke method or is the controller's method missing in your routes file?

@Heqma Can you show the contents of the FrontController please? Do you have an `__invoke` method?

**Comment by Heqma** [comment] 2021-06-01 12:39
![image](https://user-images.githubusercontent.com/71975536/120324561-0f9b4500-c2e7-11eb-84c5-1ff2284aa8e7.png)
![image](https://user-images.githubusercontent.com/71975536/120324615-1d50ca80-c2e7-11eb-9e0c-19c5e4814c0a.png)
i dont know why my route group isnt work... i have 404.. with group routes.. i

**Comment by chinleung** [comment] 2021-06-01 12:54
@Heqma There's currently an issue with prefixes. I'll be working on this soon. For the moment, you can do it without the `prefix` method.

I'll be closing this since it's a duplicate of https://github.com/chinleung/laravel-multilingual-routes/issues/50.

**Closed as completed by chinleung** 2021-06-01 12:54 UTC
Labels: question

**Comment by Heqma** [comment] 2021-06-01 13:01
Ok then... also i need to know why translate isn't work...
![image](https://user-images.githubusercontent.com/71975536/120327402-ffd13000-c2e9-11eb-83aa-a5a6078d4301.png)
![image](https://user-images.githubusercontent.com/71975536/120327517-22fbdf80-c2ea-11eb-9da6-7f8a63148014.png)

`Facade\Ignition\Exceptions\ViewException
Route [contact.store] not defined`

**Comment by chinleung** [comment] 2021-06-01 13:22
@Heqma When you use the `name` method, it adds the locale prefix to the route's name. So it would either be `pl.contact.store` or `en.contact.store`. Or you can use the helper `localized_route('contact.store')`.

You can view the list of your application's routes with `php artisan route:list` to confirm their names.

**Comment by Heqma** [comment] 2021-06-01 13:45
![image](https://user-images.githubusercontent.com/71975536/120334605-0f07ac00-c2f1-11eb-93f4-8df0ee9df237.png)


![image](https://user-images.githubusercontent.com/71975536/120334323-d49e0f00-c2f0-11eb-9541-b476431258c9.png)
![image](https://user-images.githubusercontent.com/71975536/120334779-38c0d300-c2f1-11eb-8ca5-0597e3a737e3.png)
![image](https://user-images.githubusercontent.com/71975536/120333816-5ccfe480-c2f0-11eb-9307-5509ac040494.png)
